In [5]:
import numpy as np
import pandas as pd

In [6]:
mylist = [1,2,3]
type(mylist)

list

In [7]:
np.array(mylist)

array([1, 2, 3])

In [8]:
mylist = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
arr = np.array(mylist)

In [13]:
arr.shape

(3, 3)

In [31]:
np.random.rand(5)

array([0.81226589, 0.67026042, 0.6517677 , 0.42456894, 0.65659534])

In [33]:
np.random.randn(5)

array([ 0.68120929,  1.03512507, -0.03116048,  1.93993231, -1.00518692])

In [36]:
np.random.randint(5,10,5)

array([8, 5, 6, 9, 6])

In [22]:
np.random.seed(101)
randmat = np.random.rand(5,4)
randmat

array([[0.51639863, 0.57066759, 0.02847423, 0.17152166],
       [0.68527698, 0.83389686, 0.30696622, 0.89361308],
       [0.72154386, 0.18993895, 0.55422759, 0.35213195],
       [0.1818924 , 0.78560176, 0.96548322, 0.23235366],
       [0.08356143, 0.60354842, 0.72899276, 0.27623883]])

In [27]:
df = pd.DataFrame(data = randmat, index = 'A B C D E'.split(), columns = 'X Y Z alpha'.split())
df

X         Y         Z     alpha
A  0.516399  0.570668  0.028474  0.171522
B  0.685277  0.833897  0.306966  0.893613
C  0.721544  0.189939  0.554228  0.352132
D  0.181892  0.785602  0.965483  0.232354
E  0.083561  0.603548  0.728993  0.276239

In [42]:
df.loc[['A','B']][['X','Y']]

X         Y
A  0.516399  0.570668
B  0.685277  0.833897

In [45]:
df.iloc[0:3]

X         Y         Z     alpha
A  0.516399  0.570668  0.028474  0.171522
B  0.685277  0.833897  0.306966  0.893613
C  0.721544  0.189939  0.554228  0.352132

In [49]:
df[df['Z'] > 0]

X         Y         Z     alpha
A  0.516399  0.570668  0.028474  0.171522
B  0.685277  0.833897  0.306966  0.893613
C  0.721544  0.189939  0.554228  0.352132
D  0.181892  0.785602  0.965483  0.232354
E  0.083561  0.603548  0.728993  0.276239

In [50]:
df[df['Z'] > 0]['Y']

A    0.570668
B    0.833897
C    0.189939
D    0.785602
E    0.603548
Name: Y, dtype: float64

In [57]:
df[(df['Z'] > 0) & (df['X'] > 1)]

Empty DataFrame
Columns: [X, Y, Z, alpha]
Index: []

In [59]:
df.reset_index()

index         X         Y         Z     alpha
0     A  0.516399  0.570668  0.028474  0.171522
1     B  0.685277  0.833897  0.306966  0.893613
2     C  0.721544  0.189939  0.554228  0.352132
3     D  0.181892  0.785602  0.965483  0.232354
4     E  0.083561  0.603548  0.728993  0.276239

In [60]:
df['States'] = 'GJ PB TN TS KS'.split()

In [61]:
df

X         Y         Z     alpha States
A  0.516399  0.570668  0.028474  0.171522     GJ
B  0.685277  0.833897  0.306966  0.893613     PB
C  0.721544  0.189939  0.554228  0.352132     TN
D  0.181892  0.785602  0.965483  0.232354     TS
E  0.083561  0.603548  0.728993  0.276239     KS

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X       5 non-null      float64
 1   Y       5 non-null      float64
 2   Z       5 non-null      float64
 3   alpha   5 non-null      float64
 4   States  5 non-null      object 
dtypes: float64(4), object(1)
memory usage: 412.0+ bytes


In [63]:
df.dtypes

X         float64
Y         float64
Z         float64
alpha     float64
States     object
dtype: object

In [64]:
df.describe()

X         Y         Z     alpha
count  5.000000  5.000000  5.000000  5.000000
mean   0.437735  0.596731  0.516829  0.385172
std    0.291079  0.254030  0.364086  0.291749
min    0.083561  0.189939  0.028474  0.171522
25%    0.181892  0.570668  0.306966  0.232354
50%    0.516399  0.603548  0.554228  0.276239
75%    0.685277  0.785602  0.728993  0.352132
max    0.721544  0.833897  0.965483  0.893613

In [82]:
df2 = pd.DataFrame({'A': [1,2,3,4], 'B': [5,np.nan,np.nan,7], 'C': [12, 9, 10, np.nan]})
df2

A    B     C
0  1  5.0  12.0
1  2  NaN   9.0
2  3  NaN  10.0
3  4  7.0   NaN

In [71]:
df2.dropna(axis = 0)

A    B     C
0  1  5.0  12.0

In [72]:
df2.dropna(axis = 1)

A
0  1
1  2
2  3
3  4

In [79]:
df2.dropna(thresh=1)

A    B     C
0  1  5.0  12.0
1  2  NaN   9.0
2  3  NaN  10.0
3  4  7.0   NaN

In [80]:
df2.fillna(6)

A    B     C
0  1  5.0  12.0
1  2  6.0   9.0
2  3  6.0  10.0
3  4  7.0   6.0

In [83]:
df2.fillna(df2.mean())

A    B          C
0  1  5.0  12.000000
1  2  6.0   9.000000
2  3  6.0  10.000000
3  4  7.0  10.333333

In [84]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [86]:
df3 = pd.DataFrame(data)
df3

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [89]:
df3.groupby('Company').mean().T

Company     FB   GOOG   MSFT
Sales    296.5  160.0  232.0

In [92]:
import pandas as pd
df5 = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df5

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [93]:
df5['col2'].unique()

array([444, 555, 666], dtype=int64)

In [94]:
df5['col2'].nunique()

3

In [95]:
df5['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [97]:
def times_two(number):
    return number**3

In [99]:
df5['new'] = df5['col1'].apply(times_two)

In [100]:
df5

col1  col2 col3  new
0     1   444  abc    1
1     2   555  def    8
2     3   666  ghi   27
3     4   444  xyz   64

In [103]:
dff = pd.read_csv('Data\df1.csv')
dff.head()

Unnamed: 0         A         B         C         D
0  2000-01-01  1.339091 -0.163643 -0.646443  1.041233
1  2000-01-02 -0.774984  0.137034 -0.882716 -2.253382
2  2000-01-03 -0.921037 -0.482943 -0.417100  0.478638
3  2000-01-04 -1.738808 -0.072973  0.056517  0.015085
4  2000-01-05 -0.905980  1.778576  0.381918  0.291436